"""update passcode

Revision ID: abcb01ea5cee
Revises: db385f37dcad
Create Date: 2022-05-13 04:53:09.179859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcb01ea5cee'
down_revision = 'db385f37dcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.add_column('breaks', sa.Column('work_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breaks', 'work_time')
    op.create_table('works',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='works_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='works_pkey')
    )
    # ### end Alembic commands ###
