"""update passcode

Revision ID: db385f37dcad
Revises: 2762856aa2c5
Create Date: 2022-05-13 02:48:45.955210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db385f37dcad'
down_revision = '2762856aa2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryb', sa.String(), nullable=True),
    sa.Column('break_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('work')
    op.drop_table('break')
    op.add_column('users', sa.Column('pass_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code')
    op.create_table('break',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryb', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('break_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='break_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='break_pkey')
    )
    op.create_table('work',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='work_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='work_pkey')
    )
    op.drop_table('works')
    op.drop_table('breaks')
    # ### end Alembic commands ###
